### ISSUE TITLE
Notebook outputs EXR files?

### ISSUE THREAD

**Issue by memmam** [lloydowen8/place-heatmap-2022#12]
Hello!

I was just curious why this notebook outputs the heatmap as EXR files instead of PNGs. PNGs would be easier for me to look through, as they generate thumbnails in Windows Explorer and can be opened by the Windows default image viewer 'Photos', which allows for scrubbing through images in a folder. The only program I have installed that can open EXR files is Photoshop, which doesn't have this functionality.

Unless there's some reason for EXR files to be used (which is why I'm asking), I think it would make sense to change the notebook to output PNGs so the files are easier to work with.

**Comment by lloydowen8** [comment]
This was just as a convince for me. I produced the final heatmap video in after effects and EXR files are _much_ easier and faster to process with that software. The EXR data is also convent for people using the data set in applications such as blender.

**Comment by memmam** [comment]
Understandable. Maybe as part of #4 there should be a prompt to choose between PNG or EXR.

**Comment by lloydowen8** [comment]
This issue is now covered by #3
